config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations'}
  devise_scope :user do
    delete 'delete_account/:id', to: 'users/registrations#delete_account', as: 'delete_account_user'
    delete 'users/sign_out', to: 'users/sessions#destroy'
    get 'check_email', to: 'users/sessions#check_email', as: 'check_email'
  end
  
  resources :forum_threads do
    get '/:forum_category_id', to: 'forum_threads#index'
    resources :forum_posts, module: :forum_threads do
      resources :comments
    end
    resources :comments
  end

  resources :chat_bots

  get 'users_table', to: 'all_users#index', as: 'all_users'
  post 'users_table/change_role', to: 'all_users#change_role', as: 'change_role'
  get 'logs', to: 'logs#index', as: 'logs'


  # resources :users do
  #   collection do
  #     post :import
  #   end
  # end

  root to: "forum_threads#index"
end

app/views/shared/_navbar.html.erb
<header class="navbar <%= content_for?(:navbar_style) ? yield(:navbar_style) : "navbar-default" %> navbar-static-top" role="banner">
  <div class="container">
    <div class="navbar-header">
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_url, class: "navbar-brand" do %>
        Форум
      <% end %>
      <%= link_to "Чат-бот", chat_bots_path, class: "navbar-brand" %>
      
      <% if current_user && (current_user.role == "admin" || current_user.role == "moder") %>
      
        <div class="dropdown">
          <button class="dropbtn navbar-brand">  Инструменты </button>
          <div class="dropdown-content">
            <%= link_to "Пользователи", all_users_path, class: "dropdown-item" %>
            <%= link_to "Логи", logs_path, class: "dropdown-item" %>
          </div>
        </div>
      <% end %>
    </div>

    <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Мой профиль", edit_user_registration_path %></li>
          <li><%= link_to "Выйти", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Регистрация", new_user_registration_path %></li>
          <li><%= link_to "Войти", new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>