config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations'}
  devise_scope :user do
    delete 'delete_account/:id', to: 'users/registrations#delete_account', as: 'delete_account_user'
    delete 'users/sign_out', to: 'users/sessions#destroy'
    get 'check_email', to: 'users/sessions#check_email', as: 'check_email'
  end
  
  resources :forum_threads do
    get '/:forum_category_id', to: 'forum_threads#index'
    resources :forum_posts, module: :forum_threads do
      resources :comments
    end
    resources :comments
  end

  resources :chat_bots

  get 'users_table', to: 'all_users#index', as: 'all_users'
  post 'users_table/change_role', to: 'all_users#change_role', as: 'change_role'
  get 'logs', to: 'logs#index', as: 'logs'


  # resources :users do
  #   collection do
  #     post :import
  #   end
  # end

  root to: "forum_threads#index"
end

app/controllers/all_users_controller.rb
class AllUsersController < ApplicationController
  def index
    @users = User.all
  end

  def change_role
    user = User.find(params[:id])
    user.role = params[:new_role]
    user.save!
  end
end

app/helpers/all_users_helper.rb
module AllUsersHelper
end

app/views/all_users/index.html.erb
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">id</th>
      <th scope="col">Email</th>
      <th scope="col">Создан</th>
      <th scope="col">Обновлен</th>
      <th scope="col">Имя</th>
      <th scope="col">Фамилия</th>
      <th scope="col">Курс</th>
      <th scope="col">Роль</th>
      <th scope="col">Никнейм</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
        <tr data-user-id=<%=user.id%>>
        <td><%= user.id %></td>
        <td><%= user.email %></td>
        <td><%= user.created_at %></td>
        <td><%= user.updated_at %></td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.course %></td>
        <td class="role"><%= user.role %></td>
        <td><%= user.nickname %></td>
        <td>
          <%= link_to "Удалить", delete_account_user_path(:id => user.id), method: :delete, data: { confirm: 'Вы уверены?' }, class: 'btn btn-danger btn-sm' %>
          <div class="dropdown-ut">
            <button class="btn btn-primary dropbtn-u btn-smt"> Изменить роль</button>
            <div class="dropdown-content-ut">
              <button id="moderator-link"> Модератор</button>
              <button id="user-link"> Пользователь</button>
            </div>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>