config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations'}
  devise_scope :user do
    delete 'delete_account/:id', to: 'users/registrations#delete_account', as: 'delete_account_user'
    delete 'users/sign_out', to: 'users/sessions#destroy'
    get 'check_email', to: 'users/sessions#check_email', as: 'check_email'
  end
  
  resources :forum_threads do
    get '/:forum_category_id', to: 'forum_threads#index'
    resources :forum_posts, module: :forum_threads do
      resources :comments
    end
    resources :comments
  end

  resources :chat_bots

  get 'users_table', to: 'all_users#index', as: 'all_users'
  post 'users_table/change_role', to: 'all_users#change_role', as: 'change_role'
  get 'logs', to: 'logs#index', as: 'logs'


  # resources :users do
  #   collection do
  #     post :import
  #   end
  # end

  root to: "forum_threads#index"
end

app/models/forum_thread.rb
class ForumThread < ActiveRecord::Base
    acts_as_paranoid

    belongs_to :user    
    belongs_to :forum_category
    has_many :forum_posts
    has_many :comments
    has_many :users, through: :forum_posts


    accepts_nested_attributes_for :forum_posts
  
    validates :subject, presence: true
    validates_associated :forum_posts

    def self.ransackable_attributes(auth_object = nil)
        ["created_at", "deleted_at", "id", "id_value", "subject", "updated_at", "user_id", "forum_category_id"]
    end

    def self.ransackable_associations(auth_object = nil)
        ["comments", "forum_posts", "user", "users", "forum_category"]
    end
end

app/controllers/forum_threads_controller.rb
class ForumThreadsController < ApplicationController
  # before_action :authenticate_user!, except: [:index, :show]
  before_action :set_forum_thread, except: [:index, :new, :create]

  def index
    @q = ForumThread.ransack(search_params_subject)


    @threads = @q.result
    forum_thread_ids = []
    # if (params.dig(:query, :forum_category_id).present?) && (params.dig(:query, :forum_category_id) != "")
    #   @threads = search_categories
    # else
    @threads.each do |t|
      forum_thread_ids << t.id
      forum_thread_ids = forum_thread_ids + search_comments
    end

    if params[:forum_category_id].present? # Обработка запроса из формы
      @threads = ForumThread.where(forum_category_id: params[:forum_category_id])
      respond_to do |format|
        format.html
        format.json { render json: @forum_threads }
      end
    else
      @threads = ForumThread.where(id: forum_thread_ids)
    end
  end

  def show
    @forum_post = ForumPost.new
  end

  def new
    @forum_thread = ForumThread.new
    @forum_thread.forum_posts.new
  end

  def create
    p params[:forum_category_id]
    @forum_thread = current_user.forum_threads.new forum_thread_params
    @forum_thread.forum_posts.first.user_id = current_user.id

    if @forum_thread.save
      redirect_to @forum_thread
    else
      render action: :new
    end
  end

  private

    def search_params_subject
      params.dig(:query, :subject) ? { subject_cont: params[:query][:subject] } : {}
    end

    def search_params_body
      params.dig(:query, :subject) ? { body_cont: params[:query][:subject] } : {}
    end

    def search_params_forum_category_id
      params.dig(:query, :forum_category_id) ? { forum_category_id_eq: params[:query][:forum_category_id] } : {}
    end

    def search_categories
      forum_categories_ids = []
      @qu = ForumThread.ransack(search_params_forum_category_id)
      @r = @qu.result
    end

    def search_comments
      forum_thread_ids = []
      @qu = Comment.ransack(search_params_body)
      @comments = @qu.result
      @comments.each do |c|
        forum_thread_ids << c.forum_thread_id
      end
      return forum_thread_ids
    end

    def set_forum_thread
      @forum_thread = ForumThread.find(params[:id])
    end

    def forum_thread_params
      params.require(:forum_thread).permit(:subject, :forum_category_id, forum_posts_attributes: [:body])
    end
end

app/views/forum_threads/_form.html.erb
<%= form_for @forum_thread do |f| %>
    <div class="form-group">
      <%= f.text_field :subject, placeholder: "Тема", class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.select :forum_category_id, options_for_select(ForumCategory.all.map { |c| [c.name, c.id] }, params[:forum_category_id]), { prompt: 'Выберете категорию' }, {class: "form-control"}%>
    </div>

    <%= f.fields_for :forum_posts do |p| %>
      <div class="form-group">
        <%= p.text_area :body, placeholder: "Содержание", rows: 10, class: "form-control" %>
      </div>
    <% end %>
  
    <div class="form-group">
      <%= f.submit "Создать тему", class: "btn btn-primary" %>
    </div>
<% end %>

app/views/forum_threads/_forum_thread.html.erb
<br>
<br>
<% if forum_threads.present? %>
    <div class="threads-forum">
        <% forum_threads.each do |thread| %>
            <%= link_to thread.subject, forum_thread_path(thread), class: "forum-thread-link" %>
            <br>
        <% end %> 
    </div>
<% else %>
  <p>По вашему запросу ничего не найдено.</p>
<% end %>

app/views/forum_threads/index.html.erb
<div class="container">
  <div class="pull-right">
    <%= link_to "Создать тему", new_forum_thread_path, class: "btn btn-primary" %>
  </div>
  <div class="pull-right" style="margin-right: 10px">
    <%= search_form_for @q, html: { class: "form-inline" } do |f| %>
      <%= f.search_field :subject, placeholder: "Поиск...", class: "form-control" %>
      <%= f.submit "Найти", class: "btn btn-success" %>
    <% end %>
  </div>

  <h1 class="page-header">Темы форума</h1>

  <%= form_with(url: forum_threads_path, method: 'get', id: 'forum_thread_form') do |form| %>
    <div class="field">
      <%= form.label :forum_category_id, "Выбор категорий: " %>
      <div class="select-wrapper">
        <%= form.collection_select :forum_category_id, ForumCategory.all, :id, :name, prompt: "Все", class: "form-select form-select-sm" %>
      </div>
    </div>
    <div class="actions">
      <%= form.submit "Найти", class: "btn btn-secondary" %>
    </div>
  <% end %>
  

  <% p "SSSSSSSSSSSSSSSSSS" %>
  <% p @threads %>
  <div id="forum_threads">
    <%= render partial: 'forum_thread', locals: { forum_threads: @threads } %>
  </div>

</div>

app/views/forum_threads/new.html.erb
<h1>Создание новой темы</h1>

<%= render partial: "form" %>

app/views/forum_threads/show.html.erb
<div class="container">
  <h1><%= @forum_thread.subject %></h1>
  <p class="text-muted">Категория: <%= ForumCategory.find(@forum_thread.forum_category_id).name%></p>
  <p class="text-muted">Кем создана тема: <%= @forum_thread.user.nil? ? "удалённым пользователем"  : @forum_thread.user.nickname %></p>
  <%= render @forum_thread.forum_posts %>
  <hr />
  <%= render partial: "forum_posts/form" %>
</div>